name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 0.1.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  isar_annotation: 0.1.0
  build: 
  source_gen: ^0.9.5
  analyzer: 
  glob: 
  path: ^1.6.0
  dart_style: ^1.3.0
  json_annotation: 
  dartx: 
  freezed_annotation: 

dev_dependencies:
  json_serializable: 
  build_runner: 
  freezed: 
